### ISSUE TITLE
Improve "getCurrentRotation"

### ISSUE THREAD

**Issue by estevE11** [estevE11/wab-tools#3]
We need a js specific implementation.

[getCurrentRotation](https://github.com/estevE11/wab-tools/blob/0aee08e01a714cc98885efd7af32455205bc16fc/add-rotate-image-button.js#L32)

**Comment by shadow-ryu** [comment]
Hey, I want to work on this issue but need some details :)

**Comment by estevE11** [comment]
The method gets an HTMLElement and returns it's rotation from the transform CSS property. It returns 0 if it does not have rotation property set. 

I don't like my implementation because it is an algorithm that can probably be replaced by js functions or better a algorithm. Basically I want to have the same functionality but with as few lines of code as possible.

I would work on it soon or later but you can try and I'll merge if I like it. Thanks

**Comment by estevE11** [comment]
`transformString.split('rotate(')[1].split('deg)')[0]`

**Comment by shadow-ryu** [comment]
ok sure.
